"""
Celery task: export fixture to STEP / STL / 3MF / PDF.
"""
import logging
import uuid
from app.core.celery_app import celery_app
from app.core.database import get_supabase_client
from app.core.storage import upload_export

log = logging.getLogger(__name__)


@celery_app.task(name="app.tasks.export.export_task", bind=True)
def export_task(self, project_id: str, fmt: str):
    log.info("export_task project=%s format=%s", project_id, fmt)
    sb = get_supabase_client()

    # Get latest fixture
    geom = (
        sb.table("fixture_geometries")
        .select("kcl,gltf_url")
        .eq("project_id", project_id)
        .order("version", desc=True)
        .limit(1)
        .execute()
    )
    if not geom.data:
        raise RuntimeError(f"No fixture geometry for project {project_id}")

    kcl = geom.data[0].get("kcl", "")
    gltf_url = geom.data[0].get("gltf_url", "")

    if fmt == "pdf":
        download_url = _export_pdf(project_id, sb)
    elif fmt in ("step", "stl", "3mf"):
        download_url = _export_via_zoo(project_id, kcl, fmt)
    elif fmt in ("dxf", "iges"):
        download_url = _export_dxf_iges(project_id, kcl, sb, fmt)
    else:
        raise ValueError(f"Unknown export format: {fmt}")

    return {"project_id": project_id, "format": fmt, "download_url": download_url}


def _export_via_zoo(project_id: str, kcl: str, fmt: str) -> str:
    """Ask Zoo.dev to output a different format from the same KCL."""
    import asyncio
    from app.services.zoo_service import compile_kcl_to_gltf  # reuse pattern

    # Zoo.dev supports output_format: step, stl, 3mf, gltf
    # We call it synchronously here from the Celery worker
    import httpx
    from app.core.config import settings

    if not settings.ZOO_API_KEY:
        mock_url = f"{settings.R2_PUBLIC_URL}/mock/{project_id}/export.{fmt}"
        log.warning("ZOO_API_KEY not set — returning mock URL: %s", mock_url)
        return mock_url

    from app.services.zoo_service import _zoo_url
    conv_url, extra_headers = _zoo_url("/file/conversion")
    headers = {"Authorization": f"Bearer {settings.ZOO_API_KEY}", **extra_headers}
    payload = {"src_format": "kcl", "output_format": fmt, "body": kcl}

    resp = httpx.post(
        conv_url,
        json=payload,
        headers=headers,
        timeout=60,
    )
    resp.raise_for_status()

    file_bytes = resp.content
    filename = f"{project_id}/export_{uuid.uuid4().hex[:8]}.{fmt}"
    return upload_export(project_id, filename, file_bytes, fmt)


def _export_dxf_iges(project_id: str, kcl: str, sb, fmt: str) -> str:
    """
    Export to DXF (2D projection) or IGES (neutral 3D) via OCCT.
    Falls back to Zoo.dev conversion if OCCT is unavailable.
    """
    from app.core.config import settings
    import io

    # Try OCCT-based export first
    try:
        from app.services import occt_service

        # Retrieve latest STEP from part_geometries
        step_row = (
            sb.table("part_geometries")
            .select("step_file_url")
            .eq("project_id", project_id)
            .order("created_at", desc=True)
            .limit(1)
            .execute()
        )
        step_url = step_row.data[0].get("step_file_url") if step_row.data else None

        if step_url:
            import httpx
            step_bytes = httpx.get(step_url, timeout=30).content
            if fmt == "dxf":
                out_bytes = occt_service.export_to_dxf(step_bytes)
            else:
                out_bytes = occt_service.export_to_iges(step_bytes)
            filename = f"{project_id}/export_{uuid.uuid4().hex[:8]}.{fmt}"
            return upload_export(project_id, filename, out_bytes, fmt)
    except Exception as e:
        log.warning("OCCT %s export failed, falling back to Zoo: %s", fmt, e)

    # Fallback: Zoo.dev conversion (supports iges, dxf in some versions)
    return _export_via_zoo(project_id, kcl, fmt)


def _export_pdf(project_id: str, sb) -> str:
    """Generate a simple PDF drawing using reportlab."""
    try:
        from reportlab.lib.pagesizes import A3
        from reportlab.pdfgen import canvas as rl_canvas
        import io

        buf = io.BytesIO()
        c = rl_canvas.Canvas(buf, pagesize=A3)
        w, h = A3
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, h - 80, f"ScaleCAD — Fixture Drawing")
        c.setFont("Helvetica", 10)
        c.drawString(50, h - 110, f"Project: {project_id}")
        c.drawString(50, h - 130, "Generated by ScaleCAD · scalecad.app")
        c.save()
        pdf_bytes = buf.getvalue()

        filename = f"{project_id}/drawing_{uuid.uuid4().hex[:8]}.pdf"
        return upload_export(project_id, filename, pdf_bytes, "pdf")
    except ImportError:
        log.warning("reportlab not installed — returning mock PDF URL")
        from app.core.config import settings
        return f"{settings.R2_PUBLIC_URL}/mock/{project_id}/drawing.pdf"
